# Generated by Django 2.1 on 2021-04-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField()),
                ('Name', models.CharField(max_length=10)),
                ('Roll_in', models.DateTimeField()),
                ('Roll_out', models.DateTimeField()),
                ('Attendace_time', models.FloatField(max_length=10)),
            ],
            options={
                'db_table': 'Attendance_master',
            },
        ),
        migrations.CreateModel(
            name='CNC_ID',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cnc_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer_Data',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OEE',
            fields=[
                ('OEE_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(unique_for_date=True)),
                ('A_shift', models.FloatField(max_length=10)),
                ('B_shift', models.FloatField(max_length=10)),
                ('C_shift', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operator_Attendance_Sheet',
            fields=[
                ('operator_att_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('present', models.CharField(max_length=3)),
                ('att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Attendance_Master')),
            ],
        ),
        migrations.CreateModel(
            name='Operator_Data',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100, unique='True')),
                ('email', models.CharField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Operator_master',
            },
        ),
        migrations.CreateModel(
            name='plan_downtime_table',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(unique_for_date=True)),
                ('Training', models.IntegerField()),
                ('Meeting', models.IntegerField()),
                ('Optimization', models.IntegerField()),
                ('Warm_up', models.IntegerField()),
                ('Bipros', models.IntegerField()),
                ('Sample', models.IntegerField()),
                ('waiting_fixture', models.IntegerField()),
                ('Maintenance', models.IntegerField()),
                ('program_loading', models.IntegerField()),
                ('Cnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.CNC_ID')),
                ('Operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Operator_Data')),
            ],
        ),
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('Pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(unique_for_date=True)),
                ('A_shift', models.FloatField(max_length=10)),
                ('B_shift', models.FloatField(max_length=10)),
                ('C_shift', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shift_table',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=10, unique='True')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Table',
            fields=[
                ('Type_id', models.AutoField(primary_key=True, serialize=False)),
                ('Type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unplan_downtime_table',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(unique_for_date=True)),
                ('Mechanic', models.IntegerField()),
                ('Electric', models.IntegerField()),
                ('Hydraulic', models.IntegerField()),
                ('Media', models.IntegerField()),
                ('Jig', models.IntegerField()),
                ('Waiting', models.IntegerField()),
                ('Others', models.IntegerField()),
                ('Cnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.CNC_ID')),
                ('Operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Operator_Data')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Shift_table')),
            ],
        ),
        migrations.AddField(
            model_name='plan_downtime_table',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Shift_table'),
        ),
        migrations.AddField(
            model_name='operator_data',
            name='OP_shi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Shift_table'),
        ),
        migrations.AddField(
            model_name='attendance_master',
            name='Shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNC_charts.Shift_table'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance_master',
            unique_together={('Name', 'Roll_in', 'Roll_out', 'Attendace_time', 'Shift')},
        ),
    ]
