# Generated by Django 2.1 on 2021-04-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNC_charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance_master',
            unique_together=set(),
        ),
    ]
